# Root Registry - Namespaces
# 命名空間註冊表

apiVersion: machinenativeops.io/v2
kind: Registry
metadata:
  name: root-registry-namespaces
  namespace: machinenativeops
  labels:
    machinenativeops.io/component: controlplane
    machinenativeops.io/layer: baseline
    machinenativeops.io/type: registry
  annotations:
    machinenativeops.io/description: "Registry of all registered namespaces"
    machinenativeops.io/version: "v1.0.0"
    machinenativeops.io/immutable: "false"

spec:
  # 註冊的命名空間
  namespaces:
    - name: "machinenativeops"
      description: "Root organizational namespace for MachineNativeOps platform"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "restricted"
      boundaries:
        - "machinenativeops.*"
      subnamespaces:
        - "machinenativeops.core"
        - "machinenativeops.agents"
        - "machinenativeops.baseline"
        - "machinenativeops.overlay"
        - "machinenativeops.validation"
        - "machinenativeops.controlplane"
      directoryMapping: "controlplane/baseline"
      contact: "team@machinenativeops.io"
    
    - name: "machinenativeops.core"
      description: "Core functionality namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "restricted"
      boundaries:
        - "machinenativeops.core.*"
      directoryMapping: "workspace/src/core"
      contact: "team@machinenativeops.io"
    
    - name: "machinenativeops.agents"
      description: "Agent implementations namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "machinenativeops.agents.*"
      directoryMapping: "workspace/src/agents"
      contact: "team@machinenativeops.io"
    
    - name: "machinenativeops.baseline"
      description: "Immutable governance truth namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "immutable"
      boundaries:
        - "machinenativeops.baseline.*"
      directoryMapping: "controlplane/baseline"
      contact: "team@machinenativeops.io"
    
    - name: "machinenativeops.overlay"
      description: "Writable runtime state namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "internal"
      writePolicy: "writable"
      boundaries:
        - "machinenativeops.overlay.*"
      directoryMapping: "controlplane/overlay"
      contact: "team@machinenativeops.io"
    
    - name: "machinenativeops.validation"
      description: "Validation tools and validators namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "immutable"
      boundaries:
        - "machinenativeops.validation.*"
      directoryMapping: "controlplane/baseline/validation"
      contact: "team@machinenativeops.io"
    
    - name: "machinenativeops.controlplane"
      description: "Controlplane governance namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "immutable"
      boundaries:
        - "machinenativeops.controlplane.*"
      directoryMapping: "controlplane"
      contact: "team@machinenativeops.io"
    
    - name: "chatops"
      description: "ChatOps automation framework namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "chatops.*"
      subnamespaces:
        - "chatops.commands"
        - "chatops.workflows"
        - "chatops.routing"
        - "chatops.policies"
      directoryMapping: "workspace/chatops"
      contact: "team@machinenativeops.io"
    
    - name: "chatops.commands"
      description: "ChatOps command definitions namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "chatops.commands.*"
      directoryMapping: "workspace/chatops/commands"
      contact: "team@machinenativeops.io"
    
    - name: "chatops.workflows"
      description: "ChatOps workflow definitions namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "chatops.workflows.*"
      directoryMapping: "workspace/chatops/workflows"
      contact: "team@machinenativeops.io"
    
    - name: "automation"
      description: "Automation workflows and tools namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "automation.*"
      subnamespaces:
        - "automation.workflows"
        - "automation.agents"
      directoryMapping: "workspace/automation"
      contact: "team@machinenativeops.io"
    
    - name: "workspace"
      description: "Workspace mutable work layer namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "workspace.*"
      subnamespaces:
        - "workspace.src"
        - "workspace.tooling"
        - "workspace.runtime"
        - "workspace.config"
      directoryMapping: "workspace"
      contact: "team@machinenativeops.io"
    
    - name: "workspace.src"
      description: "Workspace source code namespace"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "workspace.src.*"
      directoryMapping: "workspace/src"
      contact: "team@machinenativeops.io"
    
    - name: "workspace.tooling"
      description: "Development tools namespace (NOT governance validators)"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "public"
      writePolicy: "writable"
      boundaries:
        - "workspace.tooling.*"
      directoryMapping: "workspace/src/tooling"
      note: "Tools can CALL controlplane validators but not replace them"
      contact: "team@machinenativeops.io"
    
    - name: "workspace.runtime"
      description: "Runtime outputs namespace (logs, tmp, cache, artifacts)"
      owner: "machinenativeops-team"
      created: "2024-01-01T00:00:00Z"
      status: "active"
      visibility: "internal"
      writePolicy: "writable"
      boundaries:
        - "workspace.runtime.*"
      directoryMapping: "workspace/runtime"
      contact: "team@machinenativeops.io"

  # 保留的命名空間（不可註冊）
  reserved:
    - name: "root"
      reason: "System reserved"
    
    - name: "baseline"
      reason: "System reserved"
    
    - name: "overlay"
      reason: "System reserved"
    
    - name: "active"
      reason: "System reserved"
    
    - name: "controlplane"
      reason: "System reserved (use machinenativeops.controlplane)"
    
    - name: "system"
      reason: "System reserved"
    
    - name: "kernel"
      reason: "System reserved"
    
    - name: "admin"
      reason: "System reserved"
    
    - name: "sudo"
      reason: "System reserved"

  # 命名空間統計
  statistics:
    totalNamespaces: 14
    activeNamespaces: 14
    publicNamespaces: 12
    internalNamespaces: 2
    immutableNamespaces: 4
    writableNamespaces: 10
    lastUpdated: "2024-01-01T00:00:00Z"