# Root Specifications - Paths
# 路徑與目錄分區規範

apiVersion: machinenativeops.io/v2
kind: Specification
metadata:
  name: root-specs-paths
  namespace: machinenativeops
  labels:
    machinenativeops.io/component: controlplane
    machinenativeops.io/layer: baseline
    machinenativeops.io/type: specification
  annotations:
    machinenativeops.io/description: "Path and directory partitioning specifications"
    machinenativeops.io/version: "v1.0.0"
    machinenativeops.io/immutable: "true"

spec:
  # 根目錄結構（最小骨架）
  rootStructure:
    description: "Root directory contains ONLY boot pointers and FHS directories"
    allowedInRoot:
      bootPointers:
        - "root.bootstrap.yaml"
        - "root.env.sh"
        - "root.fs.map"
      
      fhsDirectories:
        - "/bin/"
        - "/sbin/"
        - "/etc/"
        - "/lib/"
        - "/var/"
        - "/usr/"
        - "/home/"
        - "/tmp/"
        - "/opt/"
        - "/srv/"
        - "/init.d/"
      
      gitFiles:
        - ".git/"
        - ".github/"
        - ".gitignore"
      
      projectFiles:
        - "README.md"
        - "LICENSE"
        - "CNAME"
        - ".env.example"
        - ".replit"
        - "wrangler.toml"  # symlink to workspace/config/
      
      primaryDirectories:
        - "controlplane/"
        - "workspace/"
    
    prohibitedInRoot:
      - "Governance files (must be in controlplane/baseline/)"
      - "Source code (must be in workspace/src/)"
      - "Configuration files (must be in workspace/config/ or controlplane/baseline/config/)"
      - "Documentation (must be in workspace/docs/)"
      - "Scripts (must be in workspace/src/scripts/)"
      - "Build artifacts (must be in workspace/artifacts/ or /var/)"
      - "Runtime data (must be in /var/ or workspace/runtime/)"
      - "Temporary files (must be in /tmp/ or workspace/runtime/tmp/)"
  
  # Controlplane 目錄結構
  controlplaneStructure:
    path: "./controlplane"
    description: "Immutable governance layer"
    
    baseline:
      path: "./controlplane/baseline"
      description: "Immutable governance truth (SSOT)"
      writable: false
      
      subdirectories:
        config:
          path: "./controlplane/baseline/config"
          description: "Core configuration files"
          allowedFiles:
            - "root.config.yaml"
            - "root.governance.yaml"
            - "root.modules.yaml"
            - "root.trust.yaml"
            - "root.provenance.yaml"
            - "root.integrity.yaml"
            - "root.naming-policy.yaml"
            - "root.super-execution.yaml"
            - "workspace.map.yaml"
        
        specifications:
          path: "./controlplane/baseline/specifications"
          description: "Specification files (SSOT)"
          allowedFiles:
            - "root.specs.naming.yaml"
            - "root.specs.namespace.yaml"
            - "root.specs.urn.yaml"
            - "root.specs.paths.yaml"
            - "root.specs.context.yaml"
            - "root.specs.logic.yaml"
            - "root.specs.mapping.yaml"
            - "root.specs.references.yaml"
        
        registries:
          path: "./controlplane/baseline/registries"
          description: "Registry files (data tables)"
          allowedFiles:
            - "root.registry.modules.yaml"
            - "root.registry.devices.yaml"
            - "root.registry.namespaces.yaml"
            - "root.registry.urns.yaml"
        
        validation:
          path: "./controlplane/baseline/validation"
          description: "Authoritative validators (gate/validator)"
          writable: false
          allowedFiles:
            - "gate-root-specs.yml"
            - "validate-root-specs.py"
          subdirectories:
            validators:
              path: "./controlplane/baseline/validation/validators"
              description: "Sub-validators called by validate-root-specs.py"
              allowedFiles:
                - "validate_naming.py"
                - "validate_namespace.py"
                - "validate_urn.py"
                - "validate_paths.py"
            vectors:
              path: "./controlplane/baseline/validation/vectors"
              description: "Test vectors for validation"
              allowedFiles:
                - "root.validation.vectors.yaml"
        
        integration:
          path: "./controlplane/baseline/integration"
          description: "Integration specifications"
          allowedFiles:
            - "root.integration.yaml"
        
        documentation:
          path: "./controlplane/baseline/documentation"
          description: "Governance documentation"
          allowedFiles:
            - "root.documentation.yaml"
    
    overlay:
      path: "./controlplane/overlay"
      description: "Writable runtime state"
      writable: true
      
      subdirectories:
        state:
          path: "./controlplane/overlay/state"
          description: "Runtime state files"
          writable: true
        
        evidence:
          path: "./controlplane/overlay/evidence"
          description: "Validation evidence and audit trails"
          writable: true
          allowedFiles:
            - "*.json"
            - "*.yaml"
            - "*.md"
            - "*.log"
    
    active:
      path: "./controlplane/active"
      description: "Read-only synthesized view (baseline + overlay)"
      writable: false
  
  # Workspace 目錄結構
  workspaceStructure:
    path: "./workspace"
    description: "Mutable work layer"
    writable: true
    
    subdirectories:
      src:
        path: "./workspace/src"
        description: "Source code and scripts"
        writable: true
        subdirectories:
          core:
            path: "./workspace/src/core"
            description: "Core shared logic"
          agents:
            path: "./workspace/src/agents"
            description: "Agent implementations"
          tooling:
            path: "./workspace/src/tooling"
            description: "Development tools (NOT governance validators)"
            note: "Tools can CALL controlplane validators but not replace them"
          adapters:
            path: "./workspace/src/adapters"
            description: "Integration adapters"
          scripts:
            path: "./workspace/src/scripts"
            description: "Utility scripts"
          bin:
            path: "./workspace/src/bin"
            description: "Executable binaries"
      
      services:
        path: "./workspace/services"
        description: "Service implementations"
        subdirectories:
          gateway:
            path: "./workspace/services/gateway"
            description: "API gateway service"
          connectors:
            path: "./workspace/services/connectors"
            description: "External system connectors"
          baselines:
            path: "./workspace/services/baselines"
            description: "Baseline services"
          core:
            path: "./workspace/services/core"
            description: "Core services"
      
      shared:
        path: "./workspace/shared"
        description: "Shared libraries and utilities"
        subdirectories:
          schema:
            path: "./workspace/shared/schema"
            description: "Shared schemas"
          types:
            path: "./workspace/shared/types"
            description: "Shared type definitions"
          utils:
            path: "./workspace/shared/utils"
            description: "Shared utilities"
          contracts:
            path: "./workspace/shared/contracts"
            description: "API contracts"
      
      db:
        path: "./workspace/db"
        description: "Database files"
        subdirectories:
          migrations:
            path: "./workspace/db/migrations"
            description: "Database migrations"
          seeds:
            path: "./workspace/db/seeds"
            description: "Database seed data"
          configs:
            path: "./workspace/db/configs"
            description: "Database configurations"
      
      chatops:
        path: "./workspace/chatops"
        description: "ChatOps automation framework"
        subdirectories:
          commands:
            path: "./workspace/chatops/commands"
            description: "ChatOps command definitions"
          workflows:
            path: "./workspace/chatops/workflows"
            description: "ChatOps workflow definitions"
          routing:
            path: "./workspace/chatops/routing"
            description: "ChatOps routing rules"
          runbooks:
            path: "./workspace/chatops/runbooks"
            description: "Operational runbooks"
          policies:
            path: "./workspace/chatops/policies"
            description: "Approval policies"
          adapters:
            path: "./workspace/chatops/adapters"
            description: "Platform adapters"
      
      runtime:
        path: "./workspace/runtime"
        description: "Runtime outputs (logs, tmp, cache, artifacts)"
        writable: true
        subdirectories:
          logs:
            path: "./workspace/runtime/logs"
            description: "Application logs"
          tmp:
            path: "./workspace/runtime/tmp"
            description: "Temporary files"
          cache:
            path: "./workspace/runtime/cache"
            description: "Cache files"
          artifacts:
            path: "./workspace/runtime/artifacts"
            description: "Build artifacts"
      
      config:
        path: "./workspace/config"
        description: "Application configurations"
        writable: true
      
      docs:
        path: "./workspace/docs"
        description: "Documentation"
        writable: true
      
      tests:
        path: "./workspace/tests"
        description: "Test files"
        writable: true
      
      deploy:
        path: "./workspace/deploy"
        description: "Deployment configurations"
        writable: true
      
      ops:
        path: "./workspace/ops"
        description: "Operations files"
        writable: true
      
      archive:
        path: "./workspace/archive"
        description: "Archived content"
        writable: true
      
      private:
        path: "./workspace/private"
        description: "Private configurations"
        writable: true
  
  # FHS 目錄結構
  fhsStructure:
    description: "Filesystem Hierarchy Standard directories"
    
    directories:
      bin:
        path: "/bin"
        description: "General user commands"
        writable: false
        symlinkTo: "workspace/src/bin"
      
      sbin:
        path: "/sbin"
        description: "System administration commands"
        writable: false
        symlinkTo: "controlplane/baseline/validation"
      
      etc:
        path: "/etc"
        description: "Configuration pointers"
        writable: false
        symlinkTo: "controlplane/baseline/config"
      
      lib:
        path: "/lib"
        description: "Shared libraries"
        writable: false
        symlinkTo: "workspace/shared"
      
      var:
        path: "/var"
        description: "Variable runtime data"
        writable: true
        subdirectories:
          log:
            path: "/var/log"
            description: "Log files"
            writable: true
          run:
            path: "/var/run"
            description: "Runtime state"
            writable: true
          state:
            path: "/var/state"
            description: "Persistent state"
            writable: true
          cache:
            path: "/var/cache"
            description: "Cache files"
            writable: true
          evidence:
            path: "/var/evidence"
            description: "Evidence and audit trails"
            writable: true
            symlinkTo: "controlplane/overlay/evidence"
      
      usr:
        path: "/usr"
        description: "Extended installation area"
        writable: false
        symlinkTo: "workspace"
      
      home:
        path: "/home"
        description: "User working area"
        writable: true
        symlinkTo: "workspace"
      
      tmp:
        path: "/tmp"
        description: "Temporary files"
        writable: true
      
      opt:
        path: "/opt"
        description: "Optional packages"
        writable: false
      
      srv:
        path: "/srv"
        description: "Service data"
        writable: true
        symlinkTo: "workspace/services"
      
      init_d:
        path: "/init.d"
        description: "Initialization scripts"
        writable: false
  
  # 寫入策略
  writePolicy:
    immutable:
      description: "Cannot be modified after creation"
      paths:
        - "controlplane/baseline/**"
        - "/bin/**"
        - "/sbin/**"
        - "/etc/**"
        - "/lib/**"
        - "/usr/**"
        - "/opt/**"
        - "/init.d/**"
    
    restricted:
      description: "Requires elevated permissions"
      paths:
        - "controlplane/overlay/state/**"
        - "/var/state/**"
    
    writable:
      description: "Open for general writes"
      paths:
        - "workspace/**"
        - "/var/log/**"
        - "/var/run/**"
        - "/var/cache/**"
        - "/var/evidence/**"
        - "/tmp/**"
        - "/home/**"
        - "/srv/**"
  
  # 路徑解析規則
  resolution:
    rules:
      - name: "Absolute paths"
        description: "Paths starting with / are resolved from root"
        example: "/var/log/app.log"
      
      - name: "Relative paths"
        description: "Paths not starting with / are resolved from current directory"
        example: "workspace/src/main.py"
      
      - name: "Symlink resolution"
        description: "Symlinks are resolved to their targets"
        example: "/etc -> controlplane/baseline/config"
      
      - name: "Namespace mapping"
        description: "Namespaces map to directory paths"
        example: "machinenativeops.baseline -> controlplane/baseline"
  
  # 驗證規則
  validation:
    rules:
      - name: "no-governance-in-root"
        check: "No governance files in root directory"
        message: "Governance files must be in controlplane/baseline/"
      
      - name: "no-source-in-root"
        check: "No source code in root directory"
        message: "Source code must be in workspace/src/"
      
      - name: "no-writes-to-baseline"
        check: "No writes to controlplane/baseline/"
        message: "Baseline is immutable"
      
      - name: "runtime-writes-restricted"
        check: "Runtime writes only to /var/, /tmp/, workspace/runtime/"
        message: "Runtime data must go to designated writable locations"
      
      - name: "valid-path-format"
        pattern: "^[a-z0-9/_.-]+$"
        message: "Paths must use lowercase letters, numbers, slashes, dots, hyphens, underscores"
  
  # 正例與反例
  examples:
    valid:
      - path: "controlplane/baseline/config/root.config.yaml"
        description: "Configuration in baseline"
      
      - path: "controlplane/baseline/specifications/root.specs.naming.yaml"
        description: "Specification in baseline"
      
      - path: "controlplane/baseline/validation/validate-root-specs.py"
        description: "Validator in baseline"
      
      - path: "controlplane/overlay/evidence/validation-2024-01-01.json"
        description: "Evidence in overlay"
      
      - path: "workspace/src/core/validator.py"
        description: "Source code in workspace"
      
      - path: "workspace/src/tooling/validate.py"
        description: "Development tool in workspace"
      
      - path: "workspace/chatops/commands/autofix.yaml"
        description: "ChatOps command in workspace"
      
      - path: "workspace/runtime/logs/app.log"
        description: "Runtime log in workspace"
      
      - path: "/var/log/system.log"
        description: "System log in FHS directory"
      
      - path: "/tmp/temp-file.txt"
        description: "Temporary file in FHS directory"
    
    invalid:
      - path: "root.governance.yaml"
        reason: "Governance file in root (must be in controlplane/baseline/config/)"
      
      - path: "validate.py"
        reason: "Validator in root (must be in controlplane/baseline/validation/)"
      
      - path: "workspace/src/root.config.yaml"
        reason: "Governance file in workspace (must be in controlplane/baseline/)"
      
      - path: "controlplane/baseline/config/app.log"
        reason: "Runtime data in baseline (must be in /var/ or workspace/runtime/)"
      
      - path: "controlplane/baseline/validation/temp.txt"
        reason: "Temporary file in baseline (must be in /tmp/ or workspace/runtime/tmp/)"
      
      - path: "workspace/validate-root-specs.py"
        reason: "Authoritative validator in workspace (must be in controlplane/baseline/validation/)"
      
      - path: "src/main.py"
        reason: "Source code in root (must be in workspace/src/)"
      
      - path: "config/app.yaml"
        reason: "Configuration in root (must be in workspace/config/ or controlplane/baseline/config/)"
      
      - path: "docs/README.md"
        reason: "Documentation in root (must be in workspace/docs/)"
      
      - path: "scripts/build.sh"
        reason: "Script in root (must be in workspace/src/scripts/)"