# Root Specifications - Naming
# 命名規格

apiVersion: machinenativeops.io/v2
kind: Specification
metadata:
  name: root-specs-naming
  namespace: machinenativeops
  labels:
    machinenativeops.io/component: controlplane
    machinenativeops.io/layer: baseline
    machinenativeops.io/type: specification
  annotations:
    machinenativeops.io/description: "Naming specifications and conventions"
    machinenativeops.io/version: "v1.0.0"
    machinenativeops.io/immutable: "true"

spec:
  # 命名約定
  conventions:
    files:
      root:
        prefix: "root."
        format: "kebab-case"
        pattern: "^root\\.[a-z][a-z0-9-]*\\.(yaml|yml|map|sh)$"
        extensions: ["yaml", "yml", "map", "sh"]
        examples:
          - "root.config.yaml"
          - "root.bootstrap.yaml"
          - "root.env.sh"
          - "root.fs.map"
      
      baseline:
        format: "kebab-case"
        pattern: "^[a-z][a-z0-9-]*\\.(yaml|yml|py|sh)$"
        extensions: ["yaml", "yml", "py", "sh"]
        examples:
          - "validate-root-specs.py"
          - "gate-root-specs.yml"
          - "root.registry.modules.yaml"
      
      overlay:
        format: "kebab-case"
        pattern: "^[a-z][a-z0-9-]*\\.(yaml|yml|json|log|md)$"
        extensions: ["yaml", "yml", "json", "log", "md"]
        examples:
          - "validation-evidence.json"
          - "runtime-state.yaml"
          - "audit-trail.log"
      
      workspace:
        format: "kebab-case"
        pattern: "^[a-z][a-z0-9-]*\\.[a-z0-9]+$"
        extensions: ["py", "ts", "js", "yaml", "yml", "json", "md", "txt"]
        examples:
          - "main.py"
          - "app.ts"
          - "config.yaml"
          - "README.md"
    
    directories:
      format: "kebab-case"
      pattern: "^[a-z][a-z0-9-]*$"
      noSpaces: true
      noUppercase: true
      noUnderscores: true
      examples:
        - "controlplane"
        - "workspace"
        - "baseline"
        - "overlay"
        - "src"
        - "tooling"
        - "chatops"
    
    identifiers:
      format: "kebab-case"
      pattern: "^[a-z][a-z0-9-]*$"
      minLength: 2
      maxLength: 63
      examples:
        - "core-validator"
        - "github-connector"
        - "command-router"
        - "workflow-executor"
    
    slugs:
      format: "kebab-case"
      pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      description: "URL-safe identifiers"
      examples:
        - "my-project"
        - "user-profile"
        - "api-v2"
    
    versions:
      format: "semantic"
      pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
      description: "Semantic versioning: v{major}.{minor}.{patch}"
      examples:
        - "v1.0.0"
        - "v2.1.3"
        - "v0.0.1"
        - "v10.5.2"
      rules:
        - "Must start with 'v' prefix"
        - "Major version: breaking changes"
        - "Minor version: new features (backward compatible)"
        - "Patch version: bug fixes (backward compatible)"
    
    urns:
      format: "urn:{namespace}:{resource-type}:{identifier}[:{version}]"
      pattern: "^urn:[a-z][a-z0-9-]*:[a-z][a-z0-9-]*:[a-z0-9][a-z0-9-]*(:[vV][0-9]+\\.[0-9]+\\.[0-9]+)?$"
      types: ["module", "agent", "service", "config", "workflow", "command", "policy", "schema", "template", "validator"]
      examples:
        - "urn:machinenativeops:module:core-validator:v1.0.0"
        - "urn:chatops:command:autofix:v2.1.0"
        - "urn:automation:workflow:ci-pipeline:v1.0.0"
    
    modules:
      format: "kebab-case"
      pattern: "^[a-z][a-z0-9-]*$"
      examples:
        - "core-validator"
        - "github-connector"
        - "command-router"
    
    labels:
      prefix: "machinenativeops.io/"
      format: "{prefix}{key}"
      pattern: "^machinenativeops\\.io/[a-z][a-z0-9-]*$"
      examples:
        - "machinenativeops.io/component"
        - "machinenativeops.io/layer"
        - "machinenativeops.io/type"
        - "machinenativeops.io/version"
  
  # 命名規則詳細說明
  rules:
    kebabCase:
      description: "Lowercase words separated by hyphens"
      pattern: "^[a-z][a-z0-9-]*$"
      allowed:
        - "lowercase letters (a-z)"
        - "numbers (0-9)"
        - "hyphens (-)"
      prohibited:
        - "uppercase letters (A-Z)"
        - "underscores (_)"
        - "spaces"
        - "special characters"
      examples:
        valid:
          - "my-file"
          - "user-profile"
          - "api-v2"
          - "config-2024"
        invalid:
          - "MyFile" # uppercase
          - "my_file" # underscore
          - "my file" # space
          - "my.file" # dot (except in file extensions)
    
    fileNaming:
      description: "File naming conventions"
      rules:
        - "Use kebab-case for file names"
        - "Single extension only (no double extensions)"
        - "Extension must match file type"
        - "No spaces in file names"
        - "Lowercase only"
      examples:
        valid:
          - "main.py"
          - "config.yaml"
          - "README.md"
          - "validate-root-specs.py"
        invalid:
          - "Main.py" # uppercase
          - "config.backup.yaml" # double extension
          - "my file.py" # space
          - "config_file.yaml" # underscore
    
    directoryNaming:
      description: "Directory naming conventions"
      rules:
        - "Use kebab-case for directory names"
        - "No file extensions"
        - "No spaces"
        - "Lowercase only"
        - "No trailing slashes in references"
      examples:
        valid:
          - "controlplane"
          - "workspace"
          - "src"
          - "my-project"
        invalid:
          - "ControlPlane" # uppercase
          - "work_space" # underscore
          - "my project" # space
          - "src.backup" # looks like file extension
    
    versionNaming:
      description: "Version naming conventions"
      format: "v{major}.{minor}.{patch}"
      rules:
        - "Must start with 'v' prefix"
        - "Three numeric components separated by dots"
        - "No leading zeros (except for 0 itself)"
        - "Major version for breaking changes"
        - "Minor version for new features"
        - "Patch version for bug fixes"
      examples:
        valid:
          - "v1.0.0"
          - "v2.1.3"
          - "v0.0.1"
          - "v10.5.2"
        invalid:
          - "1.0.0" # missing 'v' prefix
          - "v1.0" # missing patch version
          - "v01.00.00" # leading zeros
          - "v1.0.0-beta" # pre-release suffix (use separate field)
  
  # 驗證規則
  validation:
    rules:
      - name: "no-double-extensions"
        pattern: "^[^.]+\\.[^.]+$"
        message: "Files must have single extension"
        severity: "error"
      
      - name: "lowercase-only"
        pattern: "^[a-z0-9.-]+$"
        message: "Use lowercase letters, numbers, dots, hyphens only"
        severity: "error"
      
      - name: "no-spaces"
        pattern: "^[^\\s]+$"
        message: "No spaces allowed in names"
        severity: "error"
      
      - name: "no-underscores"
        pattern: "^[^_]+$"
        message: "Use hyphens instead of underscores"
        severity: "warning"
      
      - name: "valid-extension"
        check: "extension in allowed extensions"
        message: "File extension must be in allowed list"
        severity: "error"
      
      - name: "kebab-case-format"
        pattern: "^[a-z][a-z0-9-]*$"
        message: "Must follow kebab-case format"
        severity: "error"
      
      - name: "no-consecutive-hyphens"
        pattern: "^(?!.*--)"
        message: "Cannot contain consecutive hyphens"
        severity: "error"
      
      - name: "no-leading-trailing-hyphens"
        pattern: "^[a-z0-9].*[a-z0-9]$"
        message: "Cannot start or end with hyphen"
        severity: "error"
  
  # 保留名稱
  reserved:
    keywords:
      - "root"
      - "baseline"
      - "overlay"
      - "active"
      - "controlplane"
      - "workspace"
      - "system"
      - "kernel"
      - "admin"
      - "sudo"
    
    prefixes:
      - "root."
      - "system."
      - "kernel."
    
    extensions:
      prohibited:
        - "exe"
        - "dll"
        - "so"
        - "dylib"
      allowed:
        - "yaml"
        - "yml"
        - "json"
        - "py"
        - "ts"
        - "js"
        - "sh"
        - "md"
        - "txt"
        - "log"
  
  # 格式樣例（10+ 組正例與反例）
  examples:
    files:
      valid:
        - name: "root.config.yaml"
          description: "Root configuration file"
        
        - name: "validate-root-specs.py"
          description: "Validation script"
        
        - name: "gate-root-specs.yml"
          description: "Gate specification"
        
        - name: "main.py"
          description: "Main application file"
        
        - name: "app-config.yaml"
          description: "Application configuration"
        
        - name: "user-profile.ts"
          description: "TypeScript source file"
        
        - name: "api-v2.js"
          description: "API version 2 implementation"
        
        - name: "README.md"
          description: "Documentation file"
        
        - name: "build-script.sh"
          description: "Build automation script"
        
        - name: "test-results.json"
          description: "Test results data"
        
        - name: "error-log.txt"
          description: "Error log file"
        
        - name: "deployment-2024.yaml"
          description: "Deployment configuration"
      
      invalid:
        - name: "Root.Config.yaml"
          reason: "Contains uppercase letters"
        
        - name: "validate_root_specs.py"
          reason: "Uses underscores instead of hyphens"
        
        - name: "config.backup.yaml"
          reason: "Has double extension"
        
        - name: "my file.py"
          reason: "Contains space"
        
        - name: "Main.PY"
          reason: "Uppercase letters and extension"
        
        - name: "-config.yaml"
          reason: "Starts with hyphen"
        
        - name: "config-.yaml"
          reason: "Ends with hyphen"
        
        - name: "my--config.yaml"
          reason: "Contains consecutive hyphens"
        
        - name: "config.exe"
          reason: "Prohibited extension"
        
        - name: "1config.yaml"
          reason: "Starts with number"
    
    directories:
      valid:
        - name: "controlplane"
          description: "Governance layer directory"
        
        - name: "workspace"
          description: "Work layer directory"
        
        - name: "baseline"
          description: "Baseline directory"
        
        - name: "src"
          description: "Source code directory"
        
        - name: "my-project"
          description: "Project directory"
        
        - name: "api-v2"
          description: "API version 2 directory"
        
        - name: "user-profiles"
          description: "User profiles directory"
        
        - name: "test-data"
          description: "Test data directory"
        
        - name: "build-output"
          description: "Build output directory"
        
        - name: "config-2024"
          description: "Configuration directory"
      
      invalid:
        - name: "ControlPlane"
          reason: "Contains uppercase letters"
        
        - name: "work_space"
          reason: "Uses underscores"
        
        - name: "my project"
          reason: "Contains space"
        
        - name: "src.backup"
          reason: "Looks like file extension"
        
        - name: "-workspace"
          reason: "Starts with hyphen"
        
        - name: "workspace-"
          reason: "Ends with hyphen"
        
        - name: "my--project"
          reason: "Contains consecutive hyphens"
        
        - name: "1project"
          reason: "Starts with number"
    
    versions:
      valid:
        - version: "v1.0.0"
          description: "Initial release"
        
        - version: "v2.1.3"
          description: "Minor update with patches"
        
        - version: "v0.0.1"
          description: "Pre-release version"
        
        - version: "v10.5.2"
          description: "Major version 10"
        
        - version: "v3.0.0"
          description: "Breaking changes"
      
      invalid:
        - version: "1.0.0"
          reason: "Missing 'v' prefix"
        
        - version: "v1.0"
          reason: "Missing patch version"
        
        - version: "v01.00.00"
          reason: "Contains leading zeros"
        
        - version: "v1.0.0-beta"
          reason: "Contains pre-release suffix"
        
        - version: "V1.0.0"
          reason: "Uppercase 'V'"
    
    urns:
      valid:
        - urn: "urn:machinenativeops:module:core-validator:v1.0.0"
          description: "Complete URN with version"
        
        - urn: "urn:machinenativeops:module:core-validator"
          description: "URN without version"
        
        - urn: "urn:chatops:command:autofix:v2.1.0"
          description: "ChatOps command URN"
        
        - urn: "urn:automation:workflow:ci-pipeline:v1.0.0"
          description: "Automation workflow URN"
        
        - urn: "urn:machinenativeops:agent:github-connector:v1.0.0"
          description: "Agent URN"
      
      invalid:
        - urn: "urn:MachineNativeOps:module:core:v1.0.0"
          reason: "Namespace contains uppercase"
        
        - urn: "urn:machinenativeops:Module:core:v1.0.0"
          reason: "Resource type contains uppercase"
        
        - urn: "urn:machinenativeops:module:Core-Validator:v1.0.0"
          reason: "Identifier contains uppercase"
        
        - urn: "urn:machinenativeops:module:core_validator:v1.0.0"
          reason: "Identifier contains underscores"
        
        - urn: "urn:machinenativeops:module:core:1.0.0"
          reason: "Version missing 'v' prefix"

  # 目錄映射規則
  directoryMapping:
    root:
      description: "Root directory (minimal skeleton)"
      allowedContent:
        - "Boot pointers (root.bootstrap.yaml, root.env.sh, root.fs.map)"
        - "FHS directories (/bin, /sbin, /etc, /lib, /var, /usr, /home, /tmp, /opt, /srv, /init.d)"
        - "Primary directories (controlplane/, workspace/)"
        - "Git files (.git/, .github/, .gitignore)"
        - "Project files (README.md, LICENSE, CNAME, .env.example, .replit, wrangler.toml)"
    
    controlplane:
      description: "Governance layer (immutable)"
      path: "./controlplane"
      subdirectories:
        - "baseline/ (SSOT - immutable)"
        - "overlay/ (runtime state - writable)"
        - "active/ (synthesized view - read-only)"
    
    workspace:
      description: "Work layer (mutable)"
      path: "./workspace"
      subdirectories:
        - "src/ (source code)"
        - "services/ (service implementations)"
        - "shared/ (shared libraries)"
        - "db/ (database files)"
        - "chatops/ (ChatOps framework)"
        - "runtime/ (runtime outputs)"
        - "config/ (configurations)"
        - "docs/ (documentation)"
        - "tests/ (test files)"
        - "deploy/ (deployment configs)"
        - "ops/ (operations files)"
        - "archive/ (archived content)"
        - "private/ (private configs)"