# Root Specifications - Namespace
# 命名空間規範

apiVersion: machinenativeops.io/v2
kind: Specification
metadata:
  name: root-specs-namespace
  namespace: machinenativeops
  labels:
    machinenativeops.io/component: controlplane
    machinenativeops.io/layer: baseline
    machinenativeops.io/type: specification
  annotations:
    machinenativeops.io/description: "Namespace syntax, hierarchy, and boundary specifications"
    machinenativeops.io/version: "v1.0.0"
    machinenativeops.io/immutable: "true"

spec:
  # 命名空間語法規則
  syntax:
    pattern: "^[a-z][a-z0-9-]*$"
    minLength: 2
    maxLength: 63
    allowedCharacters:
      - "lowercase letters (a-z)"
      - "numbers (0-9)"
      - "hyphens (-)"
    prohibitedCharacters:
      - "uppercase letters (A-Z)"
      - "underscores (_)"
      - "dots (.)"
      - "spaces"
      - "special characters"
    rules:
      - "Must start with lowercase letter"
      - "Must end with lowercase letter or number"
      - "Cannot have consecutive hyphens"
      - "Cannot start or end with hyphen"
  
  # 命名空間層級結構
  hierarchy:
    levels:
      root:
        description: "Top-level organizational namespace"
        pattern: "^[a-z][a-z0-9-]{1,31}$"
        examples:
          - "machinenativeops"
          - "chatops"
          - "automation"
      
      domain:
        description: "Domain-specific namespace"
        pattern: "^[a-z][a-z0-9-]{1,31}\\.[a-z][a-z0-9-]{1,31}$"
        examples:
          - "machinenativeops.core"
          - "machinenativeops.agents"
          - "chatops.commands"
      
      subdomain:
        description: "Subdomain namespace"
        pattern: "^[a-z][a-z0-9-]{1,31}\\.[a-z][a-z0-9-]{1,31}\\.[a-z][a-z0-9-]{1,31}$"
        examples:
          - "machinenativeops.core.validation"
          - "machinenativeops.agents.github"
          - "chatops.commands.autofix"
    
    maxDepth: 5
    separator: "."
  
  # 命名空間邊界
  boundaries:
    isolation:
      description: "Namespace isolation rules"
      rules:
        - "Each namespace has exclusive ownership of its resources"
        - "Cross-namespace references must use fully qualified names"
        - "No implicit namespace inheritance"
    
    visibility:
      public:
        description: "Publicly accessible namespaces"
        pattern: "^(machinenativeops|chatops|automation).*"
      
      internal:
        description: "Internal-only namespaces"
        pattern: "^(internal|private|system).*"
      
      reserved:
        description: "Reserved system namespaces"
        namespaces:
          - "root"
          - "baseline"
          - "overlay"
          - "active"
          - "controlplane"
          - "workspace"
          - "system"
          - "kernel"
    
    writePolicy:
      immutable:
        description: "Namespaces that cannot be modified"
        namespaces:
          - "machinenativeops.baseline"
          - "machinenativeops.controlplane"
      
      restricted:
        description: "Namespaces requiring elevated permissions"
        namespaces:
          - "machinenativeops.core"
          - "machinenativeops.validation"
      
      writable:
        description: "Namespaces open for general use"
        pattern: "^(workspace|chatops|automation).*"
  
  # 命名空間映射到目錄
  directoryMapping:
    rules:
      - namespace: "machinenativeops.baseline"
        directory: "controlplane/baseline"
        writable: false
      
      - namespace: "machinenativeops.overlay"
        directory: "controlplane/overlay"
        writable: true
      
      - namespace: "machinenativeops.validation"
        directory: "controlplane/baseline/validation"
        writable: false
      
      - namespace: "workspace.src"
        directory: "workspace/src"
        writable: true
      
      - namespace: "workspace.tooling"
        directory: "workspace/src/tooling"
        writable: true
      
      - namespace: "workspace.chatops"
        directory: "workspace/chatops"
        writable: true
      
      - namespace: "workspace.runtime"
        directory: "workspace/runtime"
        writable: true
  
  # 驗證規則
  validation:
    rules:
      - name: "valid-namespace-syntax"
        pattern: "^[a-z][a-z0-9-]*$"
        message: "Namespace must start with lowercase letter and contain only lowercase letters, numbers, and hyphens"
      
      - name: "no-consecutive-hyphens"
        pattern: "^(?!.*--)"
        message: "Namespace cannot contain consecutive hyphens"
      
      - name: "no-leading-trailing-hyphens"
        pattern: "^[a-z].*[a-z0-9]$"
        message: "Namespace cannot start or end with hyphen"
      
      - name: "length-constraint"
        minLength: 2
        maxLength: 63
        message: "Namespace must be between 2 and 63 characters"
      
      - name: "not-reserved"
        reserved:
          - "root"
          - "baseline"
          - "overlay"
          - "active"
          - "controlplane"
          - "workspace"
          - "system"
          - "kernel"
        message: "Namespace cannot use reserved names"
  
  # 正例與反例
  examples:
    valid:
      - namespace: "machinenativeops"
        description: "Root organizational namespace"
      
      - namespace: "machinenativeops-core"
        description: "Core functionality namespace"
      
      - namespace: "chatops-commands"
        description: "ChatOps commands namespace"
      
      - namespace: "automation-workflows"
        description: "Automation workflows namespace"
      
      - namespace: "workspace-src"
        description: "Workspace source namespace"
      
      - namespace: "a1"
        description: "Minimal valid namespace"
      
      - namespace: "my-namespace-123"
        description: "Namespace with numbers and hyphens"
      
      - namespace: "long-namespace-with-many-words-but-still-valid"
        description: "Long but valid namespace"
      
      - namespace: "ns"
        description: "Short namespace"
      
      - namespace: "namespace-v2"
        description: "Versioned namespace"
    
    invalid:
      - namespace: "MachineNativeOps"
        reason: "Contains uppercase letters"
      
      - namespace: "machine_native_ops"
        reason: "Contains underscores"
      
      - namespace: "machine.native.ops"
        reason: "Contains dots (use hyphens instead)"
      
      - namespace: "-machinenativeops"
        reason: "Starts with hyphen"
      
      - namespace: "machinenativeops-"
        reason: "Ends with hyphen"
      
      - namespace: "machine--native"
        reason: "Contains consecutive hyphens"
      
      - namespace: "1namespace"
        reason: "Starts with number"
      
      - namespace: "n"
        reason: "Too short (minimum 2 characters)"
      
      - namespace: "root"
        reason: "Reserved system namespace"
      
      - namespace: "machine native ops"
        reason: "Contains spaces"