# Root Specifications - URN
# URN 格式與解析規範

apiVersion: machinenativeops.io/v2
kind: Specification
metadata:
  name: root-specs-urn
  namespace: machinenativeops
  labels:
    machinenativeops.io/component: controlplane
    machinenativeops.io/layer: baseline
    machinenativeops.io/type: specification
  annotations:
    machinenativeops.io/description: "URN format and resolution specifications"
    machinenativeops.io/version: "v1.0.0"
    machinenativeops.io/immutable: "true"

spec:
  # URN 格式定義
  format:
    syntax: "urn:{namespace}:{resource-type}:{identifier}[:{version}]"
    components:
      scheme:
        value: "urn"
        description: "Fixed URN scheme identifier"
        required: true
      
      namespace:
        pattern: "^[a-z][a-z0-9-]*$"
        description: "Namespace identifier (must follow namespace spec)"
        required: true
        examples:
          - "machinenativeops"
          - "chatops"
          - "automation"
      
      resourceType:
        pattern: "^[a-z][a-z0-9-]*$"
        description: "Type of resource being identified"
        required: true
        allowedTypes:
          - "module"
          - "agent"
          - "service"
          - "config"
          - "workflow"
          - "command"
          - "policy"
          - "schema"
          - "template"
          - "validator"
      
      identifier:
        pattern: "^[a-z0-9][a-z0-9-]*$"
        description: "Unique identifier within namespace and type"
        required: true
        minLength: 1
        maxLength: 128
      
      version:
        pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
        description: "Semantic version (optional)"
        required: false
        format: "v{major}.{minor}.{patch}"
        examples:
          - "v1.0.0"
          - "v2.1.3"
          - "v0.0.1"
  
  # URN 解析規則
  resolution:
    steps:
      - step: 1
        name: "Parse URN"
        description: "Split URN into components using colon separator"
        validation:
          - "Must start with 'urn:'"
          - "Must have at least 4 components (scheme:namespace:type:id)"
          - "May have optional 5th component (version)"
      
      - step: 2
        name: "Validate Namespace"
        description: "Check namespace against registered namespaces"
        validation:
          - "Namespace must exist in root.registry.namespaces.yaml"
          - "Namespace must follow syntax rules"
      
      - step: 3
        name: "Validate Resource Type"
        description: "Check resource type is allowed"
        validation:
          - "Resource type must be in allowedTypes list"
          - "Resource type must follow naming conventions"
      
      - step: 4
        name: "Validate Identifier"
        description: "Check identifier format and uniqueness"
        validation:
          - "Identifier must follow pattern rules"
          - "Identifier must be unique within namespace:type scope"
      
      - step: 5
        name: "Validate Version (if present)"
        description: "Check version format"
        validation:
          - "Version must follow semantic versioning"
          - "Version must match pattern v{major}.{minor}.{patch}"
      
      - step: 6
        name: "Resolve to Resource"
        description: "Map URN to actual resource location"
        mapping:
          - "Check root.registry.urns.yaml for registered URN"
          - "Return resource metadata and location"
  
  # URN 註冊規則
  registration:
    requirements:
      - "URN must be globally unique"
      - "URN must follow format specification"
      - "Namespace must be registered in root.registry.namespaces.yaml"
      - "Resource must exist at specified location"
      - "Metadata must include owner, description, created date"
    
    process:
      - step: 1
        action: "Validate URN format"
        tool: "validate_urn.py"
      
      - step: 2
        action: "Check uniqueness"
        tool: "Check root.registry.urns.yaml"
      
      - step: 3
        action: "Register URN"
        tool: "Add entry to root.registry.urns.yaml"
      
      - step: 4
        action: "Generate evidence"
        tool: "Create registration evidence in overlay/evidence/"
  
  # URN 類型定義
  resourceTypes:
    module:
      description: "Software module or package"
      pattern: "urn:{namespace}:module:{module-name}[:{version}]"
      examples:
        - "urn:machinenativeops:module:core-validator:v1.0.0"
        - "urn:chatops:module:command-router:v2.1.0"
    
    agent:
      description: "Autonomous agent"
      pattern: "urn:{namespace}:agent:{agent-name}[:{version}]"
      examples:
        - "urn:machinenativeops:agent:github-connector:v1.0.0"
        - "urn:automation:agent:workflow-executor:v1.2.0"
    
    service:
      description: "Service or API"
      pattern: "urn:{namespace}:service:{service-name}[:{version}]"
      examples:
        - "urn:machinenativeops:service:validation-api:v1.0.0"
        - "urn:chatops:service:command-gateway:v2.0.0"
    
    config:
      description: "Configuration file or settings"
      pattern: "urn:{namespace}:config:{config-name}[:{version}]"
      examples:
        - "urn:machinenativeops:config:root-governance:v1.0.0"
        - "urn:workspace:config:build-settings:v1.0.0"
    
    workflow:
      description: "Automated workflow"
      pattern: "urn:{namespace}:workflow:{workflow-name}[:{version}]"
      examples:
        - "urn:automation:workflow:ci-pipeline:v1.0.0"
        - "urn:chatops:workflow:autofix-flow:v1.0.0"
    
    command:
      description: "ChatOps or CLI command"
      pattern: "urn:{namespace}:command:{command-name}[:{version}]"
      examples:
        - "urn:chatops:command:autofix:v1.0.0"
        - "urn:chatops:command:rollback:v1.0.0"
    
    policy:
      description: "Governance or security policy"
      pattern: "urn:{namespace}:policy:{policy-name}[:{version}]"
      examples:
        - "urn:machinenativeops:policy:approval-policy:v1.0.0"
        - "urn:machinenativeops:policy:security-gate:v1.0.0"
    
    schema:
      description: "Data schema or structure definition"
      pattern: "urn:{namespace}:schema:{schema-name}[:{version}]"
      examples:
        - "urn:machinenativeops:schema:validation-result:v1.0.0"
        - "urn:chatops:schema:command-request:v1.0.0"
    
    template:
      description: "Template or boilerplate"
      pattern: "urn:{namespace}:template:{template-name}[:{version}]"
      examples:
        - "urn:machinenativeops:template:module-scaffold:v1.0.0"
        - "urn:automation:template:workflow-base:v1.0.0"
    
    validator:
      description: "Validation tool or checker"
      pattern: "urn:{namespace}:validator:{validator-name}[:{version}]"
      examples:
        - "urn:machinenativeops:validator:namespace-checker:v1.0.0"
        - "urn:machinenativeops:validator:urn-validator:v1.0.0"
  
  # 驗證規則
  validation:
    rules:
      - name: "valid-urn-format"
        pattern: "^urn:[a-z][a-z0-9-]*:[a-z][a-z0-9-]*:[a-z0-9][a-z0-9-]*(:[vV][0-9]+\\.[0-9]+\\.[0-9]+)?$"
        message: "URN must follow format: urn:namespace:type:identifier[:version]"
      
      - name: "valid-namespace"
        check: "namespace in registered namespaces"
        message: "Namespace must be registered in root.registry.namespaces.yaml"
      
      - name: "valid-resource-type"
        check: "resourceType in allowedTypes"
        message: "Resource type must be one of the allowed types"
      
      - name: "unique-urn"
        check: "URN not in root.registry.urns.yaml"
        message: "URN must be globally unique"
      
      - name: "valid-version-format"
        pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
        message: "Version must follow semantic versioning: v{major}.{minor}.{patch}"
  
  # 正例與反例
  examples:
    valid:
      - urn: "urn:machinenativeops:module:core-validator:v1.0.0"
        description: "Complete URN with version"
      
      - urn: "urn:machinenativeops:module:core-validator"
        description: "URN without version"
      
      - urn: "urn:chatops:command:autofix:v2.1.0"
        description: "ChatOps command URN"
      
      - urn: "urn:automation:workflow:ci-pipeline:v1.0.0"
        description: "Automation workflow URN"
      
      - urn: "urn:machinenativeops:agent:github-connector:v1.0.0"
        description: "Agent URN"
      
      - urn: "urn:workspace:config:build-settings:v1.0.0"
        description: "Configuration URN"
      
      - urn: "urn:machinenativeops:policy:approval-policy:v1.0.0"
        description: "Policy URN"
      
      - urn: "urn:machinenativeops:schema:validation-result:v1.0.0"
        description: "Schema URN"
      
      - urn: "urn:machinenativeops:template:module-scaffold:v1.0.0"
        description: "Template URN"
      
      - urn: "urn:machinenativeops:validator:namespace-checker:v1.0.0"
        description: "Validator URN"
    
    invalid:
      - urn: "urn:MachineNativeOps:module:core:v1.0.0"
        reason: "Namespace contains uppercase letters"
      
      - urn: "urn:machinenativeops:Module:core:v1.0.0"
        reason: "Resource type contains uppercase letters"
      
      - urn: "urn:machinenativeops:module:Core-Validator:v1.0.0"
        reason: "Identifier contains uppercase letters"
      
      - urn: "urn:machinenativeops:module:core_validator:v1.0.0"
        reason: "Identifier contains underscores"
      
      - urn: "urn:machinenativeops:module:core:1.0.0"
        reason: "Version missing 'v' prefix"
      
      - urn: "urn:machinenativeops:module:core:v1.0"
        reason: "Version missing patch number"
      
      - urn: "urn:machinenativeops:invalid-type:core:v1.0.0"
        reason: "Resource type not in allowed types"
      
      - urn: "machinenativeops:module:core:v1.0.0"
        reason: "Missing 'urn:' scheme"
      
      - urn: "urn:machinenativeops:module"
        reason: "Missing identifier"
      
      - urn: "urn:unregistered:module:core:v1.0.0"
        reason: "Namespace not registered"